In [1]:
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [77]:
df = pd.read_csv("roo_data.csv")

In [78]:
# Set pandas to display all columns
pd.set_option('display.max_columns', None)

In [79]:
df.head()

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,Logical quotient rating,hackathons,coding skills rating,public speaking points,can work long time before system?,self-learning capability?,Extra-courses did,certifications,workshops,talenttests taken?,olympiads,reading and writing skills,memory capability score,Interested subjects,interested career area,Job/Higher Studies?,Type of company want to settle in?,Taken inputs from seniors or elders,interested in games,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,69,63,78,87,94,94,87,84,61,9,4,0,4,8,yes,yes,yes,shell programming,cloud computing,no,yes,excellent,excellent,cloud computing,system developer,higherstudies,Web Services,no,no,Prayer books,salary,no,stubborn,Management,salary,hard worker,yes,no,Database Developer
1,78,62,73,60,71,70,73,84,91,12,7,1,2,3,yes,no,yes,machine learning,database security,no,no,poor,medium,networks,Business process analyst,job,SAaS services,yes,yes,Childrens,salary,yes,gentle,Technical,salary,hard worker,no,yes,Portal Administrator
2,71,86,91,87,61,81,72,72,94,11,1,4,1,3,yes,no,yes,app development,web technologies,no,yes,poor,excellent,hacking,developer,higherstudies,Sales and Marketing,yes,yes,Travel,Work,no,stubborn,Management,work,hard worker,no,yes,Portal Administrator
3,76,87,60,84,89,73,62,88,69,7,1,1,2,5,no,yes,no,python,data science,yes,no,medium,excellent,networks,testing,higherstudies,Testing and Maintainance Services,no,no,Romance,Work,yes,gentle,Management,work,smart worker,yes,yes,Systems Security Administrator
4,92,62,90,67,71,89,73,71,73,4,5,4,6,3,no,no,no,app development,cloud computing,no,no,poor,excellent,Computer Architecture,testing,higherstudies,product development,no,yes,Cookbooks,salary,no,stubborn,Management,work,hard worker,yes,yes,Business Systems Analyst

In [80]:
df.shape

(20000, 39)

In [81]:
df.describe()

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,Logical quotient rating,hackathons,coding skills rating,public speaking points
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,77.002300,76.948200,77.017550,77.094500,76.958200,77.015550,77.069850,76.913100,76.921450,7.985950,4.995050,2.992650,5.004750,5.012800
std,10.085697,10.101733,10.134815,10.087837,10.020088,10.168888,10.069059,10.138555,10.103494,2.593798,2.578383,2.005791,2.576831,2.588875
min,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,4.000000,1.000000,0.000000,1.000000,1.000000
25%,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,6.000000,3.000000,1.000000,3.000000,3.000000
50%,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,8.000000,5.000000,3.000000,5.000000,5.000000
75%,86.000000,86.000000,86.000000,86.000000,85.000000,86.000000,86.000000,86.000000,86.000000,10.000000,7.000000,5.000000,7.000000,7.000000
max,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,12.000000,9.000000,6.000000,9.000000,9.000000

In [82]:
df.isna().sum()

Acedamic percentage in Operating Systems    0
percentage in Algorithms                    0
Percentage in Programming Concepts          0
Percentage in Software Engineering          0
Percentage in Computer Networks             0
Percentage in Electronics Subjects          0
Percentage in Computer Architecture         0
Percentage in Mathematics                   0
Percentage in Communication skills          0
Hours working per day                       0
Logical quotient rating                     0
hackathons                                  0
coding skills rating                        0
public speaking points                      0
can work long time before system?           0
self-learning capability?                   0
Extra-courses did                           0
certifications                              0
workshops                                   0
talenttests taken?                          0
olympiads                                   0
reading and writing skills                  0
memory capability score                     0
Interested subjects                         0
interested career area                      0
Job/Higher Studies?                         0
Type of company want to settle in?          0
Taken inputs from seniors or elders         0
interested in games                         0
Interested Type of Books                    0
Salary Range Expected                       0
In a Realtionship?                          0
Gentle or Tuff behaviour?                   0
Management or Technical                     0
Salary/work                                 0
hard/smart worker                           0
worked in teams ever?                       0
Introvert                                   0
Suggested Job Role                          0
dtype: int64

In [83]:
df.duplicated().sum()

0

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Acedamic percentage in Operating Systems  20000 non-null  int64
 1   percentage in Algorithms                  20000 non-null  int64
 2   Percentage in Programming Concepts        20000 non-null  int64
 3   Percentage in Software Engineering        20000 non-null  int64
 4   Percentage in Computer Networks           20000 non-null  int64
 5   Percentage in Electronics Subjects        20000 non-null  int64
 6   Percentage in Computer Architecture       20000 non-null  int64
 7   Percentage in Mathematics                 20000 non-null  int64
 8   Percentage in Communication skills        20000 non-null  int64
 9   Hours working per day                     20000 non-null  int64
 10  Logical quotient rating                   20000 non-null  int64
 11  hackathons                                20000 non-null  int64
 12  coding skills rating                      20000 non-null  int64
 13  public speaking points                    20000 non-null  int64
 14  can work long time before system?         20000 non-null  object
 15  self-learning capability?                 20000 non-null  object
 16  Extra-courses did                         20000 non-null  object
 17  certifications                            20000 non-null  object
 18  workshops                                 20000 non-null  object
 19  talenttests taken?                        20000 non-null  object
 20  olympiads                                 20000 non-null  object
 21  reading and writing skills                20000 non-null  object
 22  memory capability score                   20000 non-null  object
 23  Interested subjects                       20000 non-null  object
 24  interested career area                    20000 non-null  object
 25  Job/Higher Studies?                       20000 non-null  object
 26  Type of company want to settle in?        20000 non-null  object
 27  Taken inputs from seniors or elders       20000 non-null  object
 28  interested in games                       20000 non-null  object
 29  Interested Type of Books                  20000 non-null  object
 30  Salary Range Expected                     20000 non-null  object
 31  In a Realtionship?                        20000 non-null  object
 32  Gentle or Tuff behaviour?                 20000 non-null  object
 33  Management or Technical                   20000 non-null  object
 34  Salary/work                               20000 non-null  object
 35  hard/smart worker                         20000 non-null  object
 36  worked in teams ever?                     20000 non-null  object
 37  Introvert                                 20000 non-null  object
 38  Suggested Job Role                        20000 non-null  object
dtypes: int64(14), object(25)
memory usage: 6.0+ MB

In [85]:
df['Suggested Job Role'].value_counts()

Network Security Administrator               1112
Network Security Engineer                     630
Network Engineer                              621
Project Manager                               602
Database Administrator                        593
Portal Administrator                          593
Information Technology Manager                591
Software Engineer                             590
UX Designer                                   589
Design & UX                                   588
Software Developer                            587
CRM Business Analyst                          584
Business Systems Analyst                      582
Database Developer                            581
Solutions Architect                           578
Software Systems Engineer                     575
Software Quality Assurance (QA) / Testing     571
Database Manager                              570
Web Developer                                 570
CRM Technical Developer                       567
Technical Support                             565
Quality Assurance Associate                   565
Data Architect                                564
Systems Security Administrator                562
Information Technology Auditor                558
Technical Services/Help Desk/Tech Support     558
Technical Engineer                            557
Applications Developer                        551
Systems Analyst                               550
E-Commerce Analyst                            546
Information Security Analyst                  543
Business Intelligence Analyst                 540
Mobile Applications Developer                 538
Programmer Analyst                            529
Name: Suggested Job Role, dtype: int64

In [86]:
# Columns to convert to dummy variables
columns_to_convert = [
    'can work long time before system?', 'self-learning capability?',
    'Extra-courses did', 'talenttests taken?', 'olympiads',
    'Taken inputs from seniors or elders', 'interested in games',
    'In a Realtionship?', 'worked in teams ever?', 'Introvert', 'Job/Higher Studies?',
    'Gentle or Tuff behaviour?', 'Management or Technical', 'Salary/work', 'hard/smart worker'
]

# Convert columns to dummy variables
dummy_columns = pd.get_dummies(df[columns_to_convert])

# Concatenate the dummy columns with the original DataFrame
df = pd.concat([df, dummy_columns], axis=1)

# Drop the original columns (optional)
df.drop(columns=columns_to_convert, inplace=True)

In [87]:
df

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,Logical quotient rating,hackathons,coding skills rating,public speaking points,certifications,workshops,reading and writing skills,memory capability score,Interested subjects,interested career area,Type of company want to settle in?,Interested Type of Books,Salary Range Expected,Suggested Job Role,can work long time before system?_no,can work long time before system?_yes,self-learning capability?_no,self-learning capability?_yes,Extra-courses did_no,Extra-courses did_yes,talenttests taken?_no,talenttests taken?_yes,olympiads_no,olympiads_yes,Taken inputs from seniors or elders_no,Taken inputs from seniors or elders_yes,interested in games_no,interested in games_yes,In a Realtionship?_no,In a Realtionship?_yes,worked in teams ever?_no,worked in teams ever?_yes,Introvert_no,Introvert_yes,Job/Higher Studies?_higherstudies,Job/Higher Studies?_job,Gentle or Tuff behaviour?_gentle,Gentle or Tuff behaviour?_stubborn,Management or Technical_Management,Management or Technical_Technical,Salary/work_salary,Salary/work_work,hard/smart worker_hard worker,hard/smart worker_smart worker
0,69,63,78,87,94,94,87,84,61,9,4,0,4,8,shell programming,cloud computing,excellent,excellent,cloud computing,system developer,Web Services,Prayer books,salary,Database Developer,0,1,0,1,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,0,0,1,1,0,1,0,1,0
1,78,62,73,60,71,70,73,84,91,12,7,1,2,3,machine learning,database security,poor,medium,networks,Business process analyst,SAaS services,Childrens,salary,Portal Administrator,0,1,1,0,0,1,1,0,1,0,0,1,0,1,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0
2,71,86,91,87,61,81,72,72,94,11,1,4,1,3,app development,web technologies,poor,excellent,hacking,developer,Sales and Marketing,Travel,Work,Portal Administrator,0,1,1,0,0,1,1,0,0,1,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0
3,76,87,60,84,89,73,62,88,69,7,1,1,2,5,python,data science,medium,excellent,networks,testing,Testing and Maintainance Services,Romance,Work,Systems Security Administrator,1,0,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,0,1,1,0,1,0,1,0,0,1,0,1
4,92,62,90,67,71,89,73,71,73,4,5,4,6,3,app development,cloud computing,poor,excellent,Computer Architecture,testing,product development,Cookbooks,salary,Business Systems Analyst,1,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,83,67,62,63,81,74,90,84,69,4,2,6,1,8,app development,cloud computing,poor,excellent,Software Engineering,system developer,Testing and Maintainance Services,Journals,Work,Technical Engineer,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,0,1,1,0,0,1,0,1,1,0,1,0,0,1
19996,80,69,83,87,82,66,66,92,67,7,8,0,9,8,full stack,game development,medium,excellent,Management,Business process analyst,Product based,Cookbooks,salary,E-Commerce Analyst,0,1,1,0,1,0,1,0,0,1,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0,1,0
19997,83,70,80,87,64,85,69,94,88,7,3,6,2,3,information security,database security,medium,excellent,networks,cloud computing,SAaS services,Drama,Work,Business Intelligence Analyst,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0
19998,68,87,91,88,66,74,61,87,61,5,1,4,9,5,full stack,cloud computing,poor,poor,IOT,testing,Cloud Services,Travel,Work,Software Quality Assurance (QA) / Testing,1,0,1,0,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0,0,1,0,1
19999,73,77,74,84,70,65,92,73,90,7,3,1,7,6,app development,database security,excellent,excellent,IOT,testing,Finance,Comics,Work,Applications Developer,0,1,0,1,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0,0,1,1,0

In [88]:
# Convert object type columns to category type
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].astype('category')

In [89]:
from sklearn.preprocessing import LabelEncoder

# Find columns with more than two unique categories
multi_category_columns = [col for col in df.columns if df[col].dtype == 'category' and len(df[col].cat.categories) > 2]

# Apply Label Encoding to columns with multiple unique categories
label_encoder = LabelEncoder()
for col in multi_category_columns:
    df[col] = label_encoder.fit_transform(df[col])

In [90]:
df

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,Logical quotient rating,hackathons,coding skills rating,public speaking points,certifications,workshops,reading and writing skills,memory capability score,Interested subjects,interested career area,Type of company want to settle in?,Interested Type of Books,Salary Range Expected,Suggested Job Role,can work long time before system?_no,can work long time before system?_yes,self-learning capability?_no,self-learning capability?_yes,Extra-courses did_no,Extra-courses did_yes,talenttests taken?_no,talenttests taken?_yes,olympiads_no,olympiads_yes,Taken inputs from seniors or elders_no,Taken inputs from seniors or elders_yes,interested in games_no,interested in games_yes,In a Realtionship?_no,In a Realtionship?_yes,worked in teams ever?_no,worked in teams ever?_yes,Introvert_no,Introvert_yes,Job/Higher Studies?_higherstudies,Job/Higher Studies?_job,Gentle or Tuff behaviour?_gentle,Gentle or Tuff behaviour?_stubborn,Management or Technical_Management,Management or Technical_Technical,Salary/work_salary,Salary/work_work,hard/smart worker_hard worker,hard/smart worker_smart worker
0,69,63,78,87,94,94,87,84,61,9,4,0,4,8,8,0,0,0,4,4,8,21,salary,7,0,1,0,1,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,0,0,1,1,0,1,0,1,0
1,78,62,73,60,71,70,73,84,91,12,7,1,2,3,5,2,2,1,7,0,4,5,salary,18,0,1,1,0,0,1,1,0,1,0,0,1,0,1,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0
2,71,86,91,87,61,81,72,72,94,11,1,4,1,3,0,7,2,0,6,2,5,29,Work,18,0,1,1,0,0,1,1,0,0,1,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0
3,76,87,60,84,89,73,62,88,69,7,1,1,2,5,6,1,1,0,7,5,7,23,Work,28,1,0,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,0,1,1,0,1,0,1,0,0,1,0,1
4,92,62,90,67,71,89,73,71,73,4,5,4,6,3,0,0,2,0,0,5,9,7,salary,2,1,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,83,67,62,63,81,74,90,84,69,4,2,6,1,8,0,0,2,0,3,4,7,17,Work,29,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,0,1,1,0,0,1,0,1,1,0,1,0,0,1
19996,80,69,83,87,82,66,66,92,67,7,8,0,9,8,2,3,1,0,2,0,3,7,salary,10,0,1,1,0,1,0,1,0,0,1,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0,1,0
19997,83,70,80,87,64,85,69,94,88,7,3,6,2,3,4,2,1,0,7,1,4,10,Work,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0
19998,68,87,91,88,66,74,61,87,61,5,1,4,9,5,2,0,2,2,1,5,1,29,Work,24,1,0,1,0,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0,0,1,0,1
19999,73,77,74,84,70,65,92,73,90,7,3,1,7,6,0,2,0,0,1,5,2,6,Work,0,0,1,0,1,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0,0,1,1,0

In [91]:
df['Suggested Job Role'].value_counts()

16    1112
17     630
15     621
20     602
6      593
18     593
13     591
23     590
32     589
9      588
22     587
3      584
2      582
7      581
26     578
25     575
24     571
8      570
33     570
4      567
31     565
21     565
5      564
28     562
12     558
30     558
29     557
0      551
27     550
10     546
11     543
1      540
14     538
19     529
Name: Suggested Job Role, dtype: int64

In [92]:
from imblearn.over_sampling import SMOTE

X = df[['Acedamic percentage in Operating Systems', 'percentage in Algorithms', 'Percentage in Programming Concepts', 'Percentage in Software Engineering', 'Percentage in Computer Networks', 'Percentage in Electronics Subjects', 'Percentage in Computer Architecture', 'Percentage in Mathematics', 'Percentage in Communication skills', 'Type of company want to settle in?', 'Interested Type of Books', 'coding skills rating', 'Interested subjects', 'Logical quotient rating', 'Hours working per day', 'certifications', 'workshops']]
y = df['Suggested Job Role']
X_cp = X.copy()
y_cp = y.copy()

In [93]:
X

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Type of company want to settle in?,Interested Type of Books,coding skills rating,Interested subjects,Logical quotient rating,Hours working per day,certifications,workshops
0,69,63,78,87,94,94,87,84,61,8,21,4,4,4,9,8,0
1,78,62,73,60,71,70,73,84,91,4,5,2,7,7,12,5,2
2,71,86,91,87,61,81,72,72,94,5,29,1,6,1,11,0,7
3,76,87,60,84,89,73,62,88,69,7,23,2,7,1,7,6,1
4,92,62,90,67,71,89,73,71,73,9,7,6,0,5,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,83,67,62,63,81,74,90,84,69,7,17,1,3,2,4,0,0
19996,80,69,83,87,82,66,66,92,67,3,7,9,2,8,7,2,3
19997,83,70,80,87,64,85,69,94,88,4,10,2,7,3,7,4,2
19998,68,87,91,88,66,74,61,87,61,1,29,9,1,1,5,2,0
19999,73,77,74,84,70,65,92,73,90,2,6,7,1,3,7,0,2

In [94]:
smote = SMOTE(random_state=42)

In [95]:
# Resample the dataset using SMOTE
X_resampled, y_resampled = smote.fit_resample(X, y)

In [96]:
y_resampled_new = y_resampled.copy()
y_resampled_new = label_encoder.inverse_transform(y_resampled_new)

In [97]:
# Display the new class distributions after applying SMOTE
print("Class distribution after SMOTE:")
print(pd.Series(y_resampled).value_counts())

Class distribution after SMOTE:
7     1112
12    1112
27    1112
16    1112
5     1112
22    1112
10    1112
30    1112
8     1112
18    1112
0     1112
6     1112
15    1112
23    1112
29    1112
17    1112
26    1112
9     1112
19    1112
13    1112
20    1112
31    1112
3     1112
11    1112
33    1112
21    1112
32    1112
14    1112
4     1112
1     1112
25    1112
2     1112
28    1112
24    1112
Name: Suggested Job Role, dtype: int64

# Decision Tree Classifier

In [98]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score

In [ ]:
# Splitting the dataset into training and testing sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

In [ ]:
# Decision Tree Classifier
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

prediction = decision_tree.predict(X_test)

print(classification_report(y_test, prediction))
print('\n')
print(confusion_matrix(y_test, prediction))

              precision    recall  f1-score   support

           0       0.32      0.30      0.31       233
           1       0.28      0.26      0.27       246
           2       0.27      0.28      0.28       214
           3       0.28      0.26      0.27       214
           4       0.29      0.29      0.29       223
           5       0.31      0.33      0.32       236
           6       0.25      0.26      0.26       201
           7       0.30      0.32      0.31       209
           8       0.24      0.28      0.26       205
           9       0.24      0.25      0.25       239
          10       0.27      0.32      0.29       203
          11       0.28      0.30      0.29       212
          12       0.34      0.29      0.31       227
          13       0.32      0.28      0.30       241
          14       0.32      0.32      0.32       225
          15       0.33      0.32      0.33       237
          16       0.05      0.04      0.04       223
          17       0.23      0.22      0.23       222
          18       0.29      0.32      0.30       221
          19       0.31      0.33      0.32       219
          20       0.30      0.27      0.28       234
          21       0.28      0.27      0.28       224
          22       0.23      0.24      0.23       220
          23       0.27      0.29      0.28       222
          24       0.33      0.33      0.33       248
          25       0.28      0.27      0.27       210
          26       0.26      0.26      0.26       217
          27       0.24      0.24      0.24       223
          28       0.31      0.29      0.30       232
          29       0.31      0.29      0.30       228
          30       0.28      0.33      0.30       201
          31       0.28      0.28      0.28       232
          32       0.29      0.26      0.27       218
          33       0.33      0.33      0.33       203

    accuracy                           0.28      7562
   macro avg       0.28      0.28      0.28      7562
weighted avg       0.28      0.28      0.28      7562



[[70  2  3 ...  5  8  5]
 [ 4 65  7 ...  5  6  1]
 [ 3  8 60 ...  3  3  9]
 ...
 [ 6  5  4 ... 66  3  2]
 [ 4  2  2 ...  8 57  5]
 [ 3  3  5 ...  1  6 67]]

In [ ]:
# Predictions
y_pred_dt = decision_tree.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

# Calculate accuracy score for Decision Tree
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print(f"Accuracy (Decision Tree): {accuracy_dt:.4f}")

Accuracy (Decision Tree): 0.2802

## Random forest

In [ ]:
# Random Forest Classifier
model = RandomForestClassifier(n_estimators=500, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500, random_state=42)

In [ ]:
prediction = model.predict(X_test)

print(classification_report(y_test, prediction))
print('\n')
print(confusion_matrix(y_test, prediction))

              precision    recall  f1-score   support

           0       0.72      0.73      0.73       233
           1       0.73      0.70      0.72       246
           2       0.62      0.68      0.65       214
           3       0.69      0.64      0.66       214
           4       0.64      0.70      0.67       223
           5       0.66      0.71      0.68       236
           6       0.68      0.63      0.65       201
           7       0.69      0.75      0.72       209
           8       0.61      0.72      0.66       205
           9       0.68      0.62      0.65       239
          10       0.63      0.77      0.69       203
          11       0.61      0.76      0.68       212
          12       0.69      0.66      0.68       227
          13       0.73      0.66      0.70       241
          14       0.72      0.76      0.74       225
          15       0.67      0.63      0.65       237
          16       0.08      0.04      0.05       223
          17       0.74      0.66      0.70       222
          18       0.64      0.74      0.69       221
          19       0.71      0.78      0.74       219
          20       0.63      0.62      0.63       234
          21       0.67      0.63      0.65       224
          22       0.65      0.69      0.67       220
          23       0.68      0.67      0.68       222
          24       0.74      0.71      0.73       248
          25       0.65      0.71      0.68       210
          26       0.74      0.69      0.71       217
          27       0.70      0.71      0.71       223
          28       0.77      0.75      0.76       232
          29       0.72      0.74      0.73       228
          30       0.67      0.69      0.68       201
          31       0.68      0.66      0.67       232
          32       0.73      0.62      0.67       218
          33       0.62      0.69      0.65       203

    accuracy                           0.67      7562
   macro avg       0.66      0.67      0.67      7562
weighted avg       0.67      0.67      0.67      7562



[[171   0   2 ...   4   2   2]
 [  2 172   3 ...   2   1   3]
 [  1   6 145 ...   0   0   2]
 ...
 [  1   3   4 ... 152   2   8]
 [  0   2   1 ...   4 135   1]
 [  2   0   1 ...   1   1 141]]

In [ ]:
y_pred_rf = model.predict(X_test)

In [99]:
# List all columns that contain the word 'Percentage'
percentage_columns = [col for col in X.columns if 'Percentage' in col]

# Divide each value in the percentage columns by 100
X[percentage_columns] = X[percentage_columns] / 100

<ipython-input-99-19c10db0bace>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[percentage_columns] = X[percentage_columns] / 100

In [ ]:
X

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Type of company want to settle in?,Interested Type of Books,coding skills rating,Interested subjects,Logical quotient rating,Hours working per day,certifications,workshops
0,69,63,0.78,0.87,0.94,0.94,0.87,0.84,0.61,8,21,4,4,4,9,8,0
1,78,62,0.73,0.60,0.71,0.70,0.73,0.84,0.91,4,5,2,7,7,12,5,2
2,71,86,0.91,0.87,0.61,0.81,0.72,0.72,0.94,5,29,1,6,1,11,0,7
3,76,87,0.60,0.84,0.89,0.73,0.62,0.88,0.69,7,23,2,7,1,7,6,1
4,92,62,0.90,0.67,0.71,0.89,0.73,0.71,0.73,9,7,6,0,5,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,83,67,0.62,0.63,0.81,0.74,0.90,0.84,0.69,7,17,1,3,2,4,0,0
19996,80,69,0.83,0.87,0.82,0.66,0.66,0.92,0.67,3,7,9,2,8,7,2,3
19997,83,70,0.80,0.87,0.64,0.85,0.69,0.94,0.88,4,10,2,7,3,7,4,2
19998,68,87,0.91,0.88,0.66,0.74,0.61,0.87,0.61,1,29,9,1,1,5,2,0
19999,73,77,0.74,0.84,0.70,0.65,0.92,0.73,0.90,2,6,7,1,3,7,0,2

In [ ]:
y_cp = label_encoder.fit_transform(y_cp)

In [ ]:
y_cp

array([ 7, 18, 18, ...,  1, 24,  0])

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X, y_resampled, test_size=0.3, random_state=42)

ValueError: Found input variables with inconsistent numbers of samples: [20000, 37808]

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((14000, 17), (6000, 17), (14000,), (6000,))

In [ ]:
import tensorflow as tf
from tensorflow import keras

class myCallback(tf.keras.callbacks.Callback):
        # Define the correct function signature for on_epoch_end
        def on_epoch_end(self, epoch, logs={}):
            if logs.get('accuracy') is not None and logs.get('accuracy') > 0.99:
                print("\nReached 99% accuracy so cancelling training!")

                # Stop training once the above condition is met
                self.model.stop_training = True

callbacks = myCallback()

In [ ]:
input_shape = X_train.shape[1]
print(input_shape)

17

In [ ]:
model = keras.Sequential([

    keras.layers.Dense(17, activation='relu', input_shape=(input_shape,)),
    keras.layers.Dense(50, activation='relu'),
    keras.layers.Dense(33, activation='softmax')
])

In [ ]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, epochs=5, validation_split=0.1, batch_size=32, callbacks=[callbacks])

Epoch 1/5
394/394 [==============================] - 3s 3ms/step - loss: nan - accuracy: 0.0275 - val_loss: nan - val_accuracy: 0.0321
Epoch 2/5
394/394 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.0274 - val_loss: nan - val_accuracy: 0.0321
Epoch 3/5
394/394 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.0274 - val_loss: nan - val_accuracy: 0.0321
Epoch 4/5
394/394 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.0274 - val_loss: nan - val_accuracy: 0.0321
Epoch 5/5
394/394 [==============================] - 2s 4ms/step - loss: nan - accuracy: 0.0274 - val_loss: nan - val_accuracy: 0.0321

In [ ]:
y_resampled_new

array([ 7, 18, 18, ..., 33, 33, 33])